"""SQLAlchemy models for every APIx table.

Importing this package registers all 21 tables on ``Base.metadata``. The
migrations are hand-written rather than autogenerated, but
``tests/integration/test_migration_matches_models.py`` asserts the two agree,
so the models here remain the readable statement of the schema.
"""

from __future__ import annotations

from schemas.models.base import (
    ALL_TABLES,
    IMMUTABLE_TABLES,
    MUTABLE_TABLES,
    NAMING_CONVENTION,
    Base,
    Entity,
    enum_check,
)
from schemas.models.collection import (
    CollectionJob,
    CollectionRequest,
    ComplianceDecision,
    RawQuote,
    RawResponse,
)
from schemas.models.derived import CleaningEvent, FareComponent, NormalisedQuote
from schemas.models.indexing import (
    BacktestRun,
    BenchmarkObservation,
    IndexContribution,
    IndexObservation,
    Publication,
)
from schemas.models.reference import Airport, LeadTimeBucket, Route, Source, SourceReview
from schemas.models.system import SystemEvent
from schemas.models.versioning import (
    BasePeriod,
    MethodologyVersion,
    RouteWeight,
    WeightSetVersion,
)

# Every mapped class, in dependency order (parents before children). Used by the
# test suite to enumerate tables and by the seed runner to truncate safely.
ALL_MODELS: tuple[type[Entity], ...] = (
    Airport,
    Route,
    LeadTimeBucket,
    Source,
    SourceReview,
    MethodologyVersion,
    BasePeriod,
    WeightSetVersion,
    RouteWeight,
    CollectionJob,
    CollectionRequest,
    ComplianceDecision,
    RawResponse,
    RawQuote,
    NormalisedQuote,
    FareComponent,
    CleaningEvent,
    IndexObservation,
    Publication,
    IndexContribution,
    BenchmarkObservation,
    BacktestRun,
    SystemEvent,
)

# The undirected companion view over `route`, created in migration 0001. It is
# a view, not a table, and is therefore excluded from table counts.
VIEWS: tuple[str, ...] = ("route_undirected",)

__all__ = [
    "ALL_MODELS",
    "ALL_TABLES",
    "IMMUTABLE_TABLES",
    "MUTABLE_TABLES",
    "NAMING_CONVENTION",
    "VIEWS",
    "Airport",
    "BacktestRun",
    "Base",
    "BasePeriod",
    "BenchmarkObservation",
    "CleaningEvent",
    "CollectionJob",
    "CollectionRequest",
    "ComplianceDecision",
    "Entity",
    "FareComponent",
    "IndexContribution",
    "IndexObservation",
    "LeadTimeBucket",
    "MethodologyVersion",
    "NormalisedQuote",
    "Publication",
    "RawQuote",
    "RawResponse",
    "Route",
    "RouteWeight",
    "Source",
    "SourceReview",
    "SystemEvent",
    "WeightSetVersion",
    "enum_check",
]
