"""0001 - initial schema: 21 tables, the uuidv7 generator and the undirected route view.

Creates the whole APIx data layer in one revision:

* ``uuidv7()`` in PL/pgSQL, the server-side twin of ``schemas.uuid7.uuid7``.
  PostgreSQL 16 has no built-in UUIDv7 generator, and it must exist before any
  table declares it as a column default.
* the database is pinned to UTC, so a naive timestamp written by any client is
  interpreted deterministically. IST is a rendering concern at the edge.
* all 21 tables, with their CHECK constraints, unique keys and indexes.
* ``route_undirected``, the view that pairs DEL-BOM with BOM-DEL. Routes are
  stored directionally (ADR-017); this view is the undirected read model on top.

Triggers live in revision 0002 and database roles in revision 0003.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-07

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# RFC 9562 section 5.7 layout: 48-bit big-endian millisecond timestamp, version
# nibble 7, 12 random bits, variant bits 0b10, then 62 random bits. Randomness
# comes from gen_random_uuid(), built in since PostgreSQL 13, so no extension is
# required.
UUIDV7_FUNCTION = """
CREATE OR REPLACE FUNCTION uuidv7() RETURNS uuid
LANGUAGE plpgsql
VOLATILE PARALLEL SAFE
AS $function$
DECLARE
    v_bytes bytea;
    v_ts    bigint;
BEGIN
    v_ts := (extract(epoch from clock_timestamp()) * 1000)::bigint;
    v_bytes := uuid_send(gen_random_uuid());
    v_bytes := overlay(v_bytes placing substring(int8send(v_ts) from 3 for 6) from 1 for 6);
    v_bytes := set_byte(v_bytes, 6, (get_byte(v_bytes, 6) & 15) | 112);
    v_bytes := set_byte(v_bytes, 8, (get_byte(v_bytes, 8) & 63) | 128);
    RETURN encode(v_bytes, 'hex')::uuid;
END;
$function$;
"""

# Storage is UTC, always. format(%L) is used rather than doubled quotes so the
# statement stays readable.
PIN_DATABASE_TO_UTC = """
DO $do$
BEGIN
    EXECUTE format('ALTER DATABASE %I SET timezone TO %L', current_database(), 'UTC');
END
$do$;
"""

# One row per undirected city pair, aggregating the two directional routes.
# The grouping key is least(origin, destination) || greatest(origin, destination),
# as specified in the build brief.
ROUTE_UNDIRECTED_VIEW = """
CREATE VIEW route_undirected AS
SELECT
    least(origin.iata, destination.iata) || '-'
        || greatest(origin.iata, destination.iata)  AS pair_code,
    least(r.origin_id, r.destination_id)            AS airport_a_id,
    greatest(r.origin_id, r.destination_id)         AS airport_b_id,
    count(*)                                        AS directional_count,
    bool_or(r.active)                               AS active,
    array_agg(r.id ORDER BY r.code)                 AS route_ids,
    array_agg(r.code ORDER BY r.code)               AS route_codes
FROM route r
JOIN airport origin      ON origin.id = r.origin_id
JOIN airport destination ON destination.id = r.destination_id
GROUP BY 1, 2, 3;
"""


def upgrade() -> None:
    op.execute(UUIDV7_FUNCTION)
    op.execute(PIN_DATABASE_TO_UTC)

    # ### commands auto generated by Alembic ###
    op.create_table('airport',
    sa.Column('iata', sa.CHAR(length=3), nullable=False),
    sa.Column('icao', sa.CHAR(length=4), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('tz', sa.Text(), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("iata ~ '^[A-Z]{3}$'", name=op.f('ck_airport_iata_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airport')),
    sa.UniqueConstraint('iata', name=op.f('uq_airport_iata'))
    )
    op.create_table('backtest_run',
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("limitations <> ''", name=op.f('ck_backtest_run_limitations_present')),
    sa.CheckConstraint('tier BETWEEN 1 AND 3', name=op.f('ck_backtest_run_tier_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_run'))
    )
    op.create_table('benchmark_observation',
    sa.Column('bench_source', sa.Text(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('ref', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('citation_url', sa.Text(), nullable=False),
    sa.Column('citation_page', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("citation_url <> ''", name=op.f('ck_benchmark_observation_citation_present')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_observation'))
    )
    op.create_table('collection_job',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('requests_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('requests_ok', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('requests_blocked', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('parse_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED')", name=op.f('ck_collection_job_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_job'))
    )
    op.create_index('ix_collection_job_started_at', 'collection_job', [sa.literal_column('started_at DESC')], unique=False)
    op.create_table('lead_time_bucket',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('lambda', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('cpi_comparable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days > 0', name=op.f('ck_lead_time_bucket_days_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_time_bucket')),
    sa.UniqueConstraint('code', name=op.f('uq_lead_time_bucket_code')),
    sa.UniqueConstraint('days', name=op.f('uq_lead_time_bucket_days'))
    )
    op.create_table('methodology_version',
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_version')),
    sa.UniqueConstraint('version', name=op.f('uq_methodology_version_version'))
    )
    op.create_table('source',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('transport', sa.Text(), nullable=False),
    sa.Column('adapter_key', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transport IN ('api', 'document', 'browser')", name=op.f('ck_source_transport')),
    sa.CheckConstraint('tier BETWEEN 1 AND 5', name=op.f('ck_source_tier_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
    sa.UniqueConstraint('code', name=op.f('uq_source_code'))
    )
    op.create_table('system_event',
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_event'))
    )
    op.create_index('ix_system_event_created_at', 'system_event', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('weight_set_version',
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_set_version')),
    sa.UniqueConstraint('version', name=op.f('uq_weight_set_version_version'))
    )
    op.create_table('index_observation',
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('bucket_id', sa.Uuid(), nullable=True),
    sa.Column('index_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('prev_index_value', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('base_period_id', sa.Uuid(), nullable=True),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('weight_set_version_id', sa.Uuid(), nullable=False),
    sa.Column('input_quote_count', sa.Integer(), nullable=False),
    sa.Column('excluded_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('imputed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('routes_in_basket', sa.Integer(), nullable=True),
    sa.Column('input_hash', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('STRATUM', 'ROUTE', 'HEADLINE')", name=op.f('ck_index_observation_level')),
    sa.CheckConstraint('index_value > 0', name=op.f('ck_index_observation_index_value_positive')),
    sa.ForeignKeyConstraint(['bucket_id'], ['lead_time_bucket.id'], name='fk_index_observation_bucket_id'),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_version.id'], name='fk_index_observation_methodology_version_id'),
    sa.ForeignKeyConstraint(['weight_set_version_id'], ['weight_set_version.id'], name='fk_index_observation_weight_set_version_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_observation')),
    sa.UniqueConstraint('obs_date', 'level', 'ref_id', 'bucket_id', 'methodology_version_id', name='uq_index_observation_identity')
    )
    op.create_table('route',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('directional', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z]{3}-[A-Z]{3}$'", name=op.f('ck_route_code_format')),
    sa.CheckConstraint('origin_id <> destination_id', name=op.f('ck_route_origin_ne_destination')),
    sa.ForeignKeyConstraint(['destination_id'], ['airport.id'], name='fk_route_destination_id'),
    sa.ForeignKeyConstraint(['origin_id'], ['airport.id'], name='fk_route_origin_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route')),
    sa.UniqueConstraint('code', name=op.f('uq_route_code'))
    )
    op.create_table('source_review',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('robots_decision', sa.Text(), nullable=True),
    sa.Column('tos_note', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict IN ('APPROVED', 'REQUIRES_LEGAL_REVIEW', 'REJECTED')", name=op.f('ck_source_review_verdict')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='fk_source_review_source_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_review'))
    )
    op.create_table('collection_request',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('bucket_id', sa.Uuid(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('collected_date', sa.Date(), nullable=False),
    sa.Column('query_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('travel_date >= collected_date', name=op.f('ck_collection_request_travel_not_before_collected')),
    sa.ForeignKeyConstraint(['bucket_id'], ['lead_time_bucket.id'], name='fk_collection_request_bucket_id'),
    sa.ForeignKeyConstraint(['job_id'], ['collection_job.id'], name='fk_collection_request_job_id'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='fk_collection_request_route_id'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='fk_collection_request_source_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_request')),
    sa.UniqueConstraint('query_hash', name=op.f('uq_collection_request_query_hash'))
    )
    op.create_table('index_contribution',
    sa.Column('index_observation_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('contribution', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['index_observation_id'], ['index_observation.id'], name='fk_index_contribution_index_observation_id'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='fk_index_contribution_route_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_contribution')),
    sa.UniqueConstraint('index_observation_id', 'route_id', name='uq_index_contribution_obs_route')
    )
    op.create_table('route_weight',
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('evidence_rung', sa.Integer(), nullable=False),
    sa.Column('evidence_ref', sa.Text(), nullable=False),
    sa.Column('evidence_retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_set_version_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('evidence_rung BETWEEN 1 AND 4', name=op.f('ck_route_weight_evidence_rung_range')),
    sa.CheckConstraint('weight > 0 AND weight <= 1', name=op.f('ck_route_weight_weight_range')),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='fk_route_weight_route_id'),
    sa.ForeignKeyConstraint(['weight_set_version_id'], ['weight_set_version.id'], name='fk_route_weight_weight_set_version_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_weight')),
    sa.UniqueConstraint('route_id', 'weight_set_version_id', name='uq_route_weight_route_set')
    )
    op.create_table('compliance_decision',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('robots_sha256', sa.Text(), nullable=True),
    sa.Column('matched_rule', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('ALLOWED', 'BLOCKED_ROBOTS', 'BLOCKED_UNREVIEWED', 'SKIPPED_DISABLED', 'DEFERRED_RATE_LIMIT')", name=op.f('ck_compliance_decision_decision')),
    sa.ForeignKeyConstraint(['request_id'], ['collection_request.id'], name='fk_compliance_decision_request_id'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='fk_compliance_decision_source_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_decision'))
    )
    op.create_index('ix_compliance_decision_source_decided', 'compliance_decision', ['source_id', sa.literal_column('decided_at DESC')], unique=False)
    op.create_table('raw_response',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('payload_ref', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['collection_request.id'], name='fk_raw_response_request_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_response')),
    sa.UniqueConstraint('request_id', 'sha256', name='uq_raw_response_request_sha256')
    )
    op.create_table('raw_quote',
    sa.Column('raw_response_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_response.id'], name='fk_raw_quote_raw_response_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_quote')),
    sa.UniqueConstraint('raw_response_id', 'ordinal', name='uq_raw_quote_response_ordinal')
    )
    op.create_table('normalised_quote',
    sa.Column('raw_quote_id', sa.Uuid(), nullable=True),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('bucket_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('carrier', sa.CHAR(length=2), nullable=False),
    sa.Column('flight_no', sa.Text(), nullable=True),
    sa.Column('departure_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('fare_brand', sa.Text(), nullable=True),
    sa.Column('total_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_date', sa.Date(), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('quality_status', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('imputation_code', sa.CHAR(length=1), server_default=sa.text("'N'"), nullable=False),
    sa.Column('missing_reason', sa.Text(), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('component_confidence', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component_confidence IS NULL OR component_confidence IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_normalised_quote_component_confidence')),
    sa.CheckConstraint("currency = 'INR'", name=op.f('ck_normalised_quote_currency_inr')),
    sa.CheckConstraint("imputation_code = 'Y' OR raw_quote_id IS NOT NULL", name=op.f('ck_normalised_quote_imputed_or_sourced')),
    sa.CheckConstraint("imputation_code IN ('N', 'Y')", name=op.f('ck_normalised_quote_imputation_code')),
    sa.CheckConstraint("missing_reason IN ('NONE', 'SCRAPER_FAILURE', 'SOURCE_BLOCKED', 'NO_FLIGHTS', 'SOLD_OUT', 'PARSE_FAILURE', 'PARTIAL_COMPONENTS', 'CHAIN_GAP')", name=op.f('ck_normalised_quote_missing_reason')),
    sa.CheckConstraint("provenance IN ('LIVE_COLLECTED', 'LICENSED_API', 'OFFICIAL_STATISTIC', 'PUBLIC_HISTORICAL', 'SIMULATED_DEMO')", name=op.f('ck_normalised_quote_provenance')),
    sa.CheckConstraint("quality_status IN ('COMPLETE', 'PARTIAL', 'SUSPICIOUS', 'UNUSABLE')", name=op.f('ck_normalised_quote_quality_status')),
    sa.CheckConstraint('total_fare > 0', name=op.f('ck_normalised_quote_total_fare_positive')),
    sa.ForeignKeyConstraint(['bucket_id'], ['lead_time_bucket.id'], name='fk_normalised_quote_bucket_id'),
    sa.ForeignKeyConstraint(['raw_quote_id'], ['raw_quote.id'], name='fk_normalised_quote_raw_quote_id'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='fk_normalised_quote_route_id'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='fk_normalised_quote_source_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalised_quote')),
    sa.UniqueConstraint('source_id', 'carrier', 'flight_no', 'departure_ts', 'fare_brand', 'collected_date', name='uq_normalised_quote_dedup')
    )
    op.create_index('ix_normalised_quote_route_bucket_date', 'normalised_quote', ['route_id', 'bucket_id', 'collected_date'], unique=False)
    op.create_table('cleaning_event',
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Numeric(), nullable=True),
    sa.Column('observed', sa.Numeric(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['normalised_quote.id'], name='fk_cleaning_event_quote_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cleaning_event'))
    )
    op.create_index('ix_cleaning_event_quote_id', 'cleaning_event', ['quote_id'], unique=False)
    op.create_table('fare_component',
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_fare_component_confidence')),
    sa.CheckConstraint("kind IN ('BASE', 'TAX', 'UDF', 'CONVENIENCE', 'OTHER')", name=op.f('ck_fare_component_kind')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_fare_component_amount_non_negative')),
    sa.ForeignKeyConstraint(['quote_id'], ['normalised_quote.id'], name='fk_fare_component_quote_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fare_component')),
    sa.UniqueConstraint('quote_id', 'kind', name='uq_fare_component_quote_kind')
    )
    # ### end Alembic commands ###

    op.execute(ROUTE_UNDIRECTED_VIEW)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS route_undirected")

    # ### commands auto generated by Alembic ###
    op.drop_table('fare_component')
    op.drop_index('ix_cleaning_event_quote_id', table_name='cleaning_event')
    op.drop_table('cleaning_event')
    op.drop_index('ix_normalised_quote_route_bucket_date', table_name='normalised_quote')
    op.drop_table('normalised_quote')
    op.drop_table('raw_quote')
    op.drop_table('raw_response')
    op.drop_index('ix_compliance_decision_source_decided', table_name='compliance_decision')
    op.drop_table('compliance_decision')
    op.drop_table('route_weight')
    op.drop_table('index_contribution')
    op.drop_table('collection_request')
    op.drop_table('source_review')
    op.drop_table('route')
    op.drop_table('index_observation')
    op.drop_table('weight_set_version')
    op.drop_index('ix_system_event_created_at', table_name='system_event')
    op.drop_table('system_event')
    op.drop_table('source')
    op.drop_table('methodology_version')
    op.drop_table('lead_time_bucket')
    op.drop_index('ix_collection_job_started_at', table_name='collection_job')
    op.drop_table('collection_job')
    op.drop_table('benchmark_observation')
    op.drop_table('backtest_run')
    op.drop_table('airport')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION IF EXISTS uuidv7()")
