#!/usr/bin/env python
"""Regenerate every evidential claim this project makes.

A reviewer should not have to take a number on trust. Every figure APIx cites -
test counts, index values, the source-permission findings, the sensitivity
analysis, the CPI benchmark - either comes from a file in `docs/evidence/` or is
reproducible by running something.

This runs all of it and writes a manifest recording what was checked, what the
result was, and what could not be verified here. A claim that cannot be
regenerated is listed as such rather than quietly omitted.

    .venv/Scripts/python scripts/build_evidence_pack.py

Network-dependent checks are skipped where there is no outbound access, and the
manifest says so. A skipped check is not a passed check.
"""

from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "docs" / "evidence" / "EVIDENCE-MANIFEST.md"


@dataclass
class Check:
    name: str
    claim: str
    command: list[str]
    passed: bool | None = None
    detail: str = ""
    optional: bool = False
    output: str = field(default="", repr=False)


CHECKS: list[Check] = [
    Check(
        name="Test suite",
        claim="Every test passes.",
        command=["-m", "pytest", "-q", "--tb=no"],
    ),
    Check(
        name="Index values have not drifted",
        claim=(
            "Hand-calculated golden values still hold: stratum 102.484143, "
            "route 100.414024, headline 100.103506, contributions summing exactly "
            "to the movement."
        ),
        command=["-m", "pytest", "tests/unit/test_index_engine_golden.py", "-q", "--tb=no"],
    ),
    Check(
        name="No bypass around the compliance gate",
        claim=(
            "A static scan finds no override flag, no permissive environment "
            "variable, and exactly one place that mints a compliance token."
        ),
        command=["-m", "pytest", "tests/unit/test_no_bypass_path_exists.py", "-q", "--tb=no"],
    ),
    Check(
        name="No float on a money path",
        claim="An AST scan finds no float arithmetic on any money-handling module.",
        command=["-m", "pytest", "tests/unit/test_no_float_in_money_path.py", "-q", "--tb=no"],
    ),
    Check(
        name="TLS verification is never disabled",
        claim="Certificate verification cannot be turned off anywhere in the codebase.",
        command=["-m", "pytest", "tests/unit/test_tls_ladder.py", "-q", "--tb=no"],
    ),
    Check(
        name="Immutability and provenance hold",
        claim=(
            "Append-only tables reject UPDATE and DELETE from the application "
            "role, and simulated data cannot reach a headline index."
        ),
        command=[
            "-m", "pytest",
            "tests/integration/test_constraints.py",
            "tests/integration/test_roles_and_privileges.py",
            "-q", "--tb=no",
        ],
    ),
    Check(
        name="Accessibility to WCAG 2.1 AA",
        claim=(
            "Every text/background pair meets 4.5:1 contrast, measured from the "
            "stylesheet tokens."
        ),
        command=["-m", "pytest", "tests/unit/test_accessibility.py", "-q", "--tb=no"],
    ),
    Check(
        name="Migrations are reversible",
        claim="The schema migrates up, down and up again cleanly.",
        command=["-m", "pytest", "tests/integration/test_migrations.py", "-q", "--tb=no"],
    ),
    Check(
        name="Types",
        claim="mypy --strict reports no issues.",
        command=["-m", "mypy", "--strict", "packages/"],
    ),
    Check(
        name="Lint",
        claim="ruff reports no issues.",
        command=["-m", "ruff", "check", "."],
    ),
    Check(
        name="Outlier sensitivity",
        claim=(
            "The outlier threshold does not affect the published index under "
            "methodology 1.1.0."
        ),
        command=["scripts/outlier_sensitivity.py"],
        optional=True,
    ),
    Check(
        name="Source permissions",
        claim=(
            "Each source's robots.txt, fetched and evaluated against the paths an "
            "adapter would request."
        ),
        command=["scripts/check_source_permissions.py"],
        optional=True,
    ),
]

#: Claims that cannot be regenerated by running anything, and why. Listed so
#: that "not in the manifest" never silently means "not checked".
UNVERIFIABLE: list[tuple[str, str]] = [
    (
        "The index measures Indian domestic airfare inflation",
        "Requires two quarters of parallel running against the CPI airfare item "
        "on real observations. No live source exists yet, so external validity "
        "is not established and is not claimed.",
    ),
    (
        "Route weights represent traffic",
        "Weights are a gravity proxy on AAI airport throughput (evidence rung 3). "
        "Airport throughput is not city-pair traffic, and the figures include "
        "international passengers. Rung 1 needs DGCA city-pair volumes.",
    ),
    (
        "The airfare item weight in CPI",
        "Not known. CPI contributions are reported as a range across an assumed "
        "weight, never as a point estimate.",
    ),
    (
        "GIGW and CERT-In conformity",
        "Requires an STQC engagement and a CERT-In empanelled audit. Automated "
        "accessibility checks reduce the findings those audits will return; they "
        "do not substitute for them.",
    ),
]


def run(check: Check) -> Check:
    command = [sys.executable, *check.command]
    try:
        completed = subprocess.run(
            command, cwd=REPO, capture_output=True, text=True, timeout=600
        )
        check.passed = completed.returncode == 0
        check.output = (completed.stdout or completed.stderr).strip()
        check.detail = check.output.splitlines()[-1] if check.output else ""
    except subprocess.TimeoutExpired:
        check.passed = False
        check.detail = "timed out"
    except OSError as exc:
        check.passed = None
        check.detail = f"could not run: {exc}"
    return check


def main() -> int:
    started = datetime.now(UTC)
    print(f"Evidence pack - {started.isoformat()}\n")

    results = []
    for check in CHECKS:
        print(f"  {check.name:<42} ", end="", flush=True)
        result = run(check)
        results.append(result)
        if result.passed is True:
            print("verified")
        elif result.passed is None:
            print("could not run")
        elif result.optional:
            print("skipped (needs network)")
        else:
            print("FAILED")

    verified = [r for r in results if r.passed]
    failed = [r for r in results if r.passed is False and not r.optional]
    skipped = [r for r in results if r.passed is not True and r.optional]

    _write_manifest(started, results)

    print(f"\n{len(verified)} verified, {len(failed)} failed, {len(skipped)} skipped")
    print(f"{len(UNVERIFIABLE)} claims recorded as not verifiable here.")
    print(f"\nManifest: {MANIFEST.relative_to(REPO)}")
    return 1 if failed else 0


def _write_manifest(started: datetime, results: list[Check]) -> None:
    lines = [
        "# Evidence manifest",
        "",
        f"Generated {started.isoformat()} by `scripts/build_evidence_pack.py`.",
        "",
        "Every claim below was checked by running something. A reviewer can "
        "regenerate this file and get the same answers, or find out that they "
        "no longer hold.",
        "",
        "## Verified",
        "",
        "| Claim | Check | Result |",
        "|---|---|---|",
    ]
    for r in results:
        if r.passed is not True:
            continue
        command = " ".join(r.command)
        lines.append(f"| {r.claim} | `{command}` | {r.detail or 'passed'} |")

    unrun = [r for r in results if r.passed is not True]
    if unrun:
        lines += [
            "",
            "## Not verified in this run",
            "",
            "A skipped check is not a passed check.",
            "",
            "| Claim | Why |",
            "|---|---|",
        ]
        for r in unrun:
            reason = (
                "needs outbound network access"
                if r.optional
                else r.detail or "failed"
            )
            lines.append(f"| {r.claim} | {reason} |")

    lines += [
        "",
        "## Not verifiable by running anything",
        "",
        "Listed so that absence from the table above never silently means "
        "*not checked*.",
        "",
        "| Claim | Why it cannot be verified here |",
        "|---|---|",
    ]
    for claim, reason in UNVERIFIABLE:
        lines.append(f"| {claim} | {reason} |")

    lines += [
        "",
        "## Standing evidence files",
        "",
        "Dated records of findings that are not re-derivable on demand, because "
        "they capture what an external source said at a moment in time:",
        "",
    ]
    evidence_dir = REPO / "docs" / "evidence"
    for path in sorted(evidence_dir.glob("*.md")):
        if path.name != MANIFEST.name:
            lines.append(f"- `{path.relative_to(REPO)}`")
    lines.append("")

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
